//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _420_476_VIVLIO.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FSPCEntities : DbContext
    {
        public FSPCEntities()
            : base("name=FSPCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Matiere> Matiere { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<Niveau> Niveau { get; set; }
        public virtual DbSet<Offer> Offer { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
