//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _420_476_VIVLIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int SenderID { get; set; }
        public int ReceiverID { get; set; }
        public string Message1 { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
